# Generated by Django 5.2.2 on 2025-06-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=50)),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(choices=[('ios', 'IOS'), ('android', 'ANDROID'), ('web', 'WEB')], default='web', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
