# Generated by Django 5.2.2 on 2025-06-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_device',
            name='created_at',
        ),
    ]
