# Generated by Django 5.2.2 on 2025-06-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsApplication', '0002_alter_user_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_device',
            name='device_type',
            field=models.CharField(choices=[('ios', 'IOS'), ('android', 'ANDROID'), ('web', 'WEB')], default='web', max_length=50),
        ),
    ]
